<html>
<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=1, maximum-scale=2, minimum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="/laminim/app.css">

    <link rel="shortcut icon" href="/favicon.ico"/>
</head>
<body>

<div id="app"></div>

<script type="text/javascript" src="/laminim/app.js"></script>
</body>
</html>
